#!/usr/bin/env python3
"""Scan expert package outputs for developer-machine paths.

This complements validate_expert.py: validate_expert checks package files,
while this script can scan runtime artifacts such as summary JSON, Markdown
reports, and Excel workbooks generated by an expert.
"""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path

import validate_expert


EXCEL_SUFFIXES = {".xlsx", ".xlsm"}
SKIP_DIRS = validate_expert.FORBIDDEN_DISTRIBUTION_DIRS | {".mypy_cache", ".pytest_cache"}
ENGINE_DIRECTORIES = {".opencode", ".mobilework-engine"}


def is_text_file(path: Path) -> bool:
    return path.suffix.lower() in validate_expert.TEXT_SCAN_SUFFIXES or path.name in validate_expert.TEXT_SCAN_NAMES


def iter_files(root: Path):
    if root.is_file():
        yield root
        return
    for path in sorted(root.rglob("*")):
        if any(part in SKIP_DIRS for part in path.relative_to(root).parts):
            continue
        if path.is_file():
            yield path


def scan_text(text: str, display_path: str, findings: list[dict[str, str]]) -> None:
    for pattern, label in validate_expert.NON_PORTABLE_TEXT_PATTERNS:
        for match in pattern.finditer(text):
            line_number = text.count("\n", 0, match.start()) + 1
            findings.append(
                {
                    "file": display_path,
                    "location": f"line {line_number}",
                    "type": label,
                    "match": match.group(0).strip(),
                }
            )


def scan_text_file(path: Path, base: Path, findings: list[dict[str, str]]) -> None:
    try:
        text = path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        return
    scan_text(text, path.relative_to(base).as_posix(), findings)


def scan_workbook(path: Path, base: Path, findings: list[dict[str, str]]) -> None:
    try:
        from openpyxl import load_workbook
    except ImportError as exc:  # pragma: no cover - host dependent
        raise SystemExit("openpyxl is required to scan Excel artifacts.") from exc
    try:
        wb = load_workbook(path, read_only=True, data_only=True)
    except Exception as exc:  # pragma: no cover - corrupt workbook path
        findings.append(
            {
                "file": path.relative_to(base).as_posix(),
                "location": "workbook",
                "type": "unreadable workbook",
                "match": str(exc),
            }
        )
        return
    try:
        for ws in wb.worksheets:
            for row in ws.iter_rows():
                for cell in row:
                    if isinstance(cell.value, str):
                        location = f"{ws.title}!{cell.coordinate}"
                        scan_text(cell.value, f"{path.relative_to(base).as_posix()}:{location}", findings)
    finally:
        wb.close()


def scan_root(root: Path) -> list[dict[str, str]]:
    base = root if root.is_dir() else root.parent
    findings: list[dict[str, str]] = []
    for path in iter_files(root):
        suffix = path.suffix.lower()
        if suffix in EXCEL_SUFFIXES:
            scan_workbook(path, base, findings)
        elif is_text_file(path):
            scan_text_file(path, base, findings)
    return findings


def validate_runtime_artifact_root(
    lexical_root: Path,
    resolved_root: Path,
    resolved_workspace_root: Path,
) -> dict[str, str] | None:
    try:
        resolved_relative_root = resolved_root.relative_to(resolved_workspace_root)
    except ValueError:
        return {
            "file": str(lexical_root),
            "location": "path",
            "type": "artifact outside workspace",
            "match": str(resolved_root),
        }

    engine_segment = next(
        (
            part
            for part in lexical_root.parts + resolved_relative_root.parts
            if part.casefold() in ENGINE_DIRECTORIES
        ),
        None,
    )
    if engine_segment is not None:
        return {
            "file": str(lexical_root),
            "location": "path",
            "type": "runtime artifact under engine directory",
            "match": engine_segment,
        }
    return None


def lexical_absolute(path: Path) -> Path:
    return Path(os.path.normpath(os.path.abspath(path.expanduser())))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--workspace-root",
        type=Path,
        help="Require runtime artifact roots to stay inside this workspace and outside engine directories",
    )
    parser.add_argument("paths", nargs="+", type=Path, help="Artifact files or directories to scan")
    args = parser.parse_args()

    all_findings: list[dict[str, str]] = []
    resolved_workspace_root = (
        lexical_absolute(args.workspace_root).resolve() if args.workspace_root else None
    )
    for root in args.paths:
        lexical_root = lexical_absolute(root)
        root = lexical_root.resolve()
        if resolved_workspace_root is not None:
            location_finding = validate_runtime_artifact_root(
                lexical_root,
                root,
                resolved_workspace_root,
            )
            if location_finding is not None:
                all_findings.append(location_finding)
                continue
        if not root.exists():
            all_findings.append(
                {
                    "file": str(root),
                    "location": "path",
                    "type": "missing path",
                    "match": str(root),
                }
            )
            continue
        all_findings.extend(scan_root(root))

    print(json.dumps({"ok": not all_findings, "findings": all_findings}, ensure_ascii=False, indent=2))
    return 0 if not all_findings else 1


if __name__ == "__main__":
    raise SystemExit(main())
